server:
  port: 7454
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #    liquibase:
    #      change-log: classpath:liquibase/db/changelog/db.changelog-master.yaml
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:mysql://localhost:3306/tutor_app
    #     passwords to DB
    password: 123456
#    password: sapereaude8
  jpa:
    hibernate: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    ddl-auto: update
jwt:
  secret: ${JWT_SECRET_TOKEN:MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCKXsBGx7l8ze1Dqlbgt3sFPYgBBWg4lwDb5KbB1KBvQB0mMZIu/9qZUToFyztbYZCJ7Utb9bYfvkDsVDa9Bqn4zkoSJUDQqac2uRHo3Up4WFMzhT2EB1iKZRYAteBG7Dr+i0e/kPes+3uentGPnBeQHGfZCgzAG1cYNoxB/PJ7uwIDAQAB}
  expire: 3600000